package generate

import (
	"fmt"
	"strings"

	"github.com/aeswibon/manga-cdc/configure/manifest"
	"github.com/aeswibon/manga-cdc/configure/presets"
)

func renderGuide(m manifest.Manifest) (string, error) {
	var b strings.Builder

	b.WriteString("# manga-cdc Setup Guide\n\n")
	b.WriteString("Generated by the configure wizard. Follow these steps to get started.\n\n")

	b.WriteString("## Prerequisites\n\n")
	switch m.Tier {
	case manifest.TierLocal:
		b.WriteString("- Docker & Docker Compose\n")
		b.WriteString("- Go 1.26+ (optional, for running the scraper on the host)\n")
		b.WriteString("- Java 21+ (optional, for running the notification service on the host)\n\n")
	case manifest.TierProduction:
		b.WriteString("- Docker & Docker Compose or Kubernetes (Helm)\n")
		b.WriteString("- Managed PostgreSQL and Kafka or QStash credentials\n")
		b.WriteString("- Container images published to a registry (or build locally)\n\n")
	}

	b.WriteString("## Environment\n\n")
	b.WriteString("1. Copy the environment file:\n")
	b.WriteString("   ```bash\n   cp .env.example .env\n   ```\n")
	b.WriteString("2. Fill in the values in `.env`.\n")
	if m.Tier == manifest.TierProduction {
		b.WriteString("   - Derive `SPRING_DATASOURCE_URL` from `DATABASE_URL` (`postgres://` → `jdbc:postgresql://`).\n")
		for _, note := range presets.DatabaseHints(m.Database.Preset).SetupNotes {
			b.WriteString(fmt.Sprintf("   - %s\n", note))
		}
		switch m.Eventing.Backend {
		case manifest.EventingKafka:
			for _, note := range presets.KafkaHints(m.Eventing.Preset).SetupNotes {
				b.WriteString(fmt.Sprintf("   - %s\n", note))
			}
		case manifest.EventingQStash:
			for _, note := range presets.QStashHints(m.Eventing.Preset).SetupNotes {
				b.WriteString(fmt.Sprintf("   - %s\n", note))
			}
		}
	}
	b.WriteString("\n")

	switch m.Tier {
	case manifest.TierLocal:
		b.WriteString("## Local Development (Docker Compose)\n\n")
		b.WriteString("Postgres and Redpanda are included. The scraper publishes chapter events directly to Redpanda.\n\n")
		b.WriteString("```bash\ndocker compose up --build -d\n```\n\n")
		b.WriteString("```bash\ndocker compose logs scraper\n```\n\n")
	case manifest.TierProduction:
		if m.HasDeployTarget("docker-compose-prod") {
			b.WriteString("## Production Deployment (Docker Compose)\n\n")
			b.WriteString("Only application services are included — database and eventing run on your managed providers.\n\n")
			b.WriteString("```bash\ndocker compose -f docker-compose.prod.yml pull\ndocker compose -f docker-compose.prod.yml up -d\n```\n\n")
		}
		if m.HasDeployTarget("helm") {
			b.WriteString("## Kubernetes (Helm)\n\n")
			b.WriteString("```bash\nhelm upgrade --install manga-cdc ./helm/manga-cdc \\\n  --values ./helm/manga-cdc/values-override.yaml \\\n  --namespace manga-cdc --create-namespace\n```\n\n")
		}
		b.WriteString("## Cloud infrastructure (Terraform)\n\n")
		b.WriteString("Cloud-specific Terraform modules (GCP, AWS, Azure) are planned for a future release.\n\n")
	}

	b.WriteString("## Verification\n\n")
	b.WriteString("```bash\n")
	if m.Tier == manifest.TierLocal {
		b.WriteString("docker compose ps\n")
	} else if m.HasDeployTarget("docker-compose-prod") {
		b.WriteString("docker compose -f docker-compose.prod.yml ps\n")
	}
	b.WriteString("curl http://localhost:2112/metrics | grep scraper_\n")
	b.WriteString("curl http://localhost:8080/actuator/health\n")
	b.WriteString("```\n\n")

	b.WriteString("## Troubleshooting\n\n")
	b.WriteString("- Scraper skips Kafka publish when `KAFKA_BROKERS` is empty.\n")
	b.WriteString("- Notification service health may report `DOWN` when Kafka or database credentials are missing.\n\n")

	b.WriteString("## Adding Manga Sources\n\n")
	b.WriteString("Implement the `SourceAdapter` interface in `scraper/internal/adapter/`.\n")

	return b.String(), nil
}

func writeGuide(m manifest.Manifest) error {
	content, err := renderGuide(m)
	if err != nil {
		return err
	}
	return writePlainFile("SETUP.md", content)
}
