package generate

import (
	"os"
	"path/filepath"
	"strings"
)

func renderGuide(cfg Config) (string, error) {
	var b strings.Builder

	b.WriteString("# manga-cdc Setup Guide\n\n")
	b.WriteString("Generated by the configure wizard. Follow these steps to get started.\n\n")

	b.WriteString("## Prerequisites\n\n")
	b.WriteString("- Docker & Docker Compose\n")
	b.WriteString("- Go 1.23+ (for running the scraper locally)\n")
	b.WriteString("- Java 21+ (for running the notification service locally)\n\n")

	b.WriteString("## Environment\n\n")
	b.WriteString("1. Copy the environment file:\n")
	b.WriteString("   ```bash\n   cp .env.example .env\n   ```\n")
	b.WriteString("2. Fill in the values in `.env`:\n")
	b.WriteString("   - Database URL (default works for Docker Compose)\n")
	switch cfg.Eventing {
	case EventingKafka, EventingBoth:
		b.WriteString("   - `KAFKA_BROKERS`, `KAFKA_USERNAME`, `KAFKA_PASSWORD` (if using Kafka)\n")
	}
	switch cfg.Eventing {
	case EventingQStash, EventingBoth:
		b.WriteString("   - `QSTASH_TOKEN`, `QSTASH_DESTINATION_URL` (if using QStash)\n")
	}
	for _, n := range cfg.Notifiers {
		switch n {
		case "discord":
			b.WriteString("   - `DISCORD_WEBHOOK_URL` — create a Discord webhook in your server's Integrations settings\n")
		case "slack":
			b.WriteString("   - `SLACK_WEBHOOK_URL` — create a Slack incoming webhook in your workspace\n")
		case "telegram":
			b.WriteString("   - `TELEGRAM_BOT_TOKEN` and `TELEGRAM_CHAT_ID` — create a bot via @BotFather\n")
		}
	}
	b.WriteString("\n")

	for _, dep := range cfg.Deployments {
		switch dep {
		case "local-compose":
			b.WriteString("## Local Development (Docker Compose)\n\n")
			b.WriteString("```bash\n")
			b.WriteString("docker compose up --build -d\n")
			b.WriteString("```\n\n")
			b.WriteString("Check the scraper is running:\n")
			b.WriteString("```bash\n")
			b.WriteString("docker compose logs scraper\n")
			b.WriteString("```\n\n")

		case "prod-compose":
			b.WriteString("## Production Deployment (Docker Compose)\n\n")
			b.WriteString("On your VM:\n")
			b.WriteString("```bash\n")
			b.WriteString("# Clone the repo\n")
			b.WriteString("git clone https://github.com/aeswibon/manga-cdc.git\n")
			b.WriteString("cd manga-cdc\n")
			b.WriteString("\n")
			b.WriteString("# Set your .env file with real values\n")
			b.WriteString("# Then pull and start\n")
			b.WriteString("docker compose -f docker-compose.prod.yml pull\n")
			b.WriteString("docker compose -f docker-compose.prod.yml up -d\n")
			b.WriteString("```\n\n")

		case "helm":
			b.WriteString("## Kubernetes (Helm)\n\n")
			b.WriteString("```bash\n")
			b.WriteString("helm upgrade --install manga-cdc ./helm/manga-cdc \\\n")
			b.WriteString("  --values ./helm/manga-cdc/values-override.yaml \\\n")
			b.WriteString("  --namespace manga-cdc --create-namespace\n")
			b.WriteString("```\n\n")

		case "terraform":
			b.WriteString("## GCP Infrastructure (Terraform)\n\n")
			b.WriteString("```bash\n")
			b.WriteString("cd terraform\n")
			b.WriteString("terraform init\n")
			b.WriteString("terraform plan -var-file=terraform.tfvars\n")
			b.WriteString("terraform apply -var-file=terraform.tfvars\n")
			b.WriteString("```\n\n")
		}
	}

	b.WriteString("## Verification\n\n")
	b.WriteString("```bash\n")
	b.WriteString("# Check container status\n")
	b.WriteString("docker compose ps\n")
	b.WriteString("\n")
	b.WriteString("# Check scraper metrics\n")
	b.WriteString("curl http://localhost:2112/metrics | grep scraper_\n")
	b.WriteString("\n")
	b.WriteString("# Check notification service health\n")
	b.WriteString("curl http://localhost:8080/actuator/health\n")
	b.WriteString("```\n\n")

	b.WriteString("## Adding Manga Sources\n\n")
	b.WriteString("Implement the `SourceAdapter` interface in `scraper/internal/adapter/`.\n")
	b.WriteString("See existing adapters (MangaDex, MangaFire, etc.) for reference.\n")

	return b.String(), nil
}

func writeGuide(cfg Config) error {
	content, err := renderGuide(cfg)
	if err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(RootDir, "SETUP.md"), []byte(content), 0644)
}
