package generate

import (
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

type helmData struct {
	KafkaEnabled  bool
	QStashEnabled bool
	Notifiers     map[string]bool
}

const helmTemplate = `# Generated by configure wizard
eventing:
  kafka:
    enabled: {{ .KafkaEnabled }}
  qstash:
    enabled: {{ .QStashEnabled }}

notifiers:
{{- range $name, $enabled := .Notifiers }}
  {{ $name }}: {{ $enabled }}
{{- end }}
`

func renderHelmValues(cfg Config) (string, error) {
	data := helmData{
		KafkaEnabled:  cfg.Eventing == EventingKafka || cfg.Eventing == EventingBoth,
		QStashEnabled: cfg.Eventing == EventingQStash || cfg.Eventing == EventingBoth,
		Notifiers:     make(map[string]bool),
	}
	for _, n := range []string{"discord", "slack", "telegram"} {
		data.Notifiers[n] = false
	}
	for _, n := range cfg.Notifiers {
		data.Notifiers[n] = true
	}

	tmpl, err := template.New("helm").Parse(helmTemplate)
	if err != nil {
		return "", err
	}

	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func writeHelmValues(cfg Config) error {
	content, err := renderHelmValues(cfg)
	if err != nil {
		return err
	}
	dir := filepath.Join(RootDir, "helm", "manga-cdc")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "values-override.yaml"), []byte(content), 0644)
}
