package generate

import (
	"fmt"
	"strings"
	"text/template"

	"github.com/aeswibon/manga-cdc/configure/manifest"
)

type helmData struct {
	Tier          string
	DatabaseURL   string
	DatabaseJDBC  string
	KafkaEnabled  bool
	QStashEnabled bool
	KafkaBrokers  string
	KafkaTopic    string
	KafkaUsername string
	KafkaPassword string
	Notifiers     map[string]bool
	InfraPostgres bool
	InfraRedpanda bool
	InfraConnect  bool
}

const helmTemplate = `# Generated by manga-cdc configure
tier: {{ .Tier }}

database:
  external: true
  url: {{ quote .DatabaseURL }}
  jdbcUrl: {{ quote .DatabaseJDBC }}

eventing:
  kafka:
    enabled: {{ .KafkaEnabled }}
    brokers: {{ quote .KafkaBrokers }}
    topic: {{ quote .KafkaTopic }}
    username: {{ quote .KafkaUsername }}
    password: {{ quote .KafkaPassword }}
  qstash:
    enabled: {{ .QStashEnabled }}

infra:
  postgres: {{ .InfraPostgres }}
  redpanda: {{ .InfraRedpanda }}
  connect: {{ .InfraConnect }}

notifiers:
{{- range $name, $enabled := .Notifiers }}
  {{ $name }}: {{ $enabled }}
{{- end }}
`

func renderHelmValues(m manifest.Manifest) (string, error) {
	if m.Tier != manifest.TierProduction {
		return "", fmt.Errorf("helm: production tier only")
	}

	data := helmData{
		Tier:          string(m.Tier),
		DatabaseURL:   m.Database.URL,
		DatabaseJDBC:  postgresToJDBC(m.Database.URL),
		KafkaEnabled:  m.Eventing.Backend == manifest.EventingKafka,
		QStashEnabled: m.Eventing.Backend == manifest.EventingQStash,
		KafkaBrokers:  m.Eventing.Kafka.Brokers,
		KafkaTopic:    defaultString(m.Eventing.Kafka.Topic, "mangacdc.public.chapters"),
		KafkaUsername: m.Eventing.Kafka.Username,
		KafkaPassword: m.Eventing.Kafka.Password,
		Notifiers:     notifierMap(m.Notifiers),
	}

	tmpl, err := template.New("helm").Funcs(template.FuncMap{
		"quote": func(s string) string {
			return fmt.Sprintf("%q", s)
		},
	}).Parse(helmTemplate)
	if err != nil {
		return "", err
	}
	var buf strings.Builder
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", err
	}
	return buf.String(), nil
}

func notifierMap(selected []string) map[string]bool {
	all := map[string]bool{"discord": false, "slack": false, "telegram": false}
	for _, n := range selected {
		all[n] = true
	}
	return all
}

func postgresToJDBC(url string) string {
	switch {
	case strings.HasPrefix(url, "postgres://"):
		return "jdbc:postgresql://" + strings.TrimPrefix(url, "postgres://")
	case strings.HasPrefix(url, "postgresql://"):
		return "jdbc:postgresql://" + strings.TrimPrefix(url, "postgresql://")
	default:
		return ""
	}
}

func writeHelmValues(m manifest.Manifest) error {
	content, err := renderHelmValues(m)
	if err != nil {
		return err
	}
	return writePlainFile("helm/manga-cdc/values-override.yaml", content)
}
