package generate

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

func renderTerraformTfvars(cfg Config) (string, error) {
	var b strings.Builder

	b.WriteString("# Generated by configure wizard\n")
	b.WriteString(fmt.Sprintf("eventing_type = %q\n", cfg.Eventing.String()))

	notifiers := make([]string, len(cfg.Notifiers))
	for i, n := range cfg.Notifiers {
		notifiers[i] = fmt.Sprintf("%q", n)
	}
	b.WriteString(fmt.Sprintf("notifiers     = [%s]\n", strings.Join(notifiers, ", ")))

	return b.String(), nil
}

func writeTerraformTfvars(cfg Config) error {
	content, err := renderTerraformTfvars(cfg)
	if err != nil {
		return err
	}
	dir := filepath.Join(RootDir, "terraform")
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(filepath.Join(dir, "terraform.tfvars"), []byte(content), 0644)
}
