package generate

import (
	"fmt"
	"os"
	"path/filepath"
)

const generatedHeader = "# Generated by manga-cdc configure — do not edit; re-run `go run ./configure generate`\n\n"

var RootDir = "."

func writeFileAtomic(path string, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(dir, ".cfg-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)

	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}

func writeGeneratedFile(relPath, body string) error {
	if body != "" && body[0] != '#' {
		body = generatedHeader + body
	}
	return writeFileAtomic(filepath.Join(RootDir, relPath), body)
}

func writePlainFile(relPath, body string) error {
	return writeFileAtomic(filepath.Join(RootDir, relPath), body)
}

func manifestPathDefault() string {
	return filepath.Join(RootDir, "manga-cdc.config.yaml")
}

func saveManifestErr(err error) error {
	return fmt.Errorf("manifest: %w", err)
}
