// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: scraper/internal/adapter/mangapluspb/mangaplus_api.proto

package mangapluspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Language int32

const (
	Language_ENGLISH       Language = 0
	Language_SPANISH       Language = 1
	Language_FRENCH        Language = 2
	Language_INDONESIAN    Language = 3
	Language_PORTUGUESE_BR Language = 4
	Language_RUSSIAN       Language = 5
	Language_THAI          Language = 6
	Language_GERMAN        Language = 7
	Language_ITALIAN       Language = 8
	Language_VIETNAMESE    Language = 9
)

// Enum value maps for Language.
var (
	Language_name = map[int32]string{
		0: "ENGLISH",
		1: "SPANISH",
		2: "FRENCH",
		3: "INDONESIAN",
		4: "PORTUGUESE_BR",
		5: "RUSSIAN",
		6: "THAI",
		7: "GERMAN",
		8: "ITALIAN",
		9: "VIETNAMESE",
	}
	Language_value = map[string]int32{
		"ENGLISH":       0,
		"SPANISH":       1,
		"FRENCH":        2,
		"INDONESIAN":    3,
		"PORTUGUESE_BR": 4,
		"RUSSIAN":       5,
		"THAI":          6,
		"GERMAN":        7,
		"ITALIAN":       8,
		"VIETNAMESE":    9,
	}
)

func (x Language) Enum() *Language {
	p := new(Language)
	*p = x
	return p
}

func (x Language) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Language) Descriptor() protoreflect.EnumDescriptor {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_enumTypes[0].Descriptor()
}

func (Language) Type() protoreflect.EnumType {
	return &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_enumTypes[0]
}

func (x Language) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Language.Descriptor instead.
func (Language) EnumDescriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{0}
}

type ErrorResult_Action int32

const (
	ErrorResult_DEFAULT        ErrorResult_Action = 0
	ErrorResult_UNAUTHORIZED   ErrorResult_Action = 1
	ErrorResult_MAINTENANCE    ErrorResult_Action = 2
	ErrorResult_GEOIP_BLOCKING ErrorResult_Action = 3
)

// Enum value maps for ErrorResult_Action.
var (
	ErrorResult_Action_name = map[int32]string{
		0: "DEFAULT",
		1: "UNAUTHORIZED",
		2: "MAINTENANCE",
		3: "GEOIP_BLOCKING",
	}
	ErrorResult_Action_value = map[string]int32{
		"DEFAULT":        0,
		"UNAUTHORIZED":   1,
		"MAINTENANCE":    2,
		"GEOIP_BLOCKING": 3,
	}
)

func (x ErrorResult_Action) Enum() *ErrorResult_Action {
	p := new(ErrorResult_Action)
	*p = x
	return p
}

func (x ErrorResult_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorResult_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_enumTypes[1].Descriptor()
}

func (ErrorResult_Action) Type() protoreflect.EnumType {
	return &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_enumTypes[1]
}

func (x ErrorResult_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorResult_Action.Descriptor instead.
func (ErrorResult_Action) EnumDescriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{1, 0}
}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*Response_Success
	//	*Response_Error
	Result        isResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{0}
}

func (x *Response) GetResult() isResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *Response) GetSuccess() *SuccessResult {
	if x != nil {
		if x, ok := x.Result.(*Response_Success); ok {
			return x.Success
		}
	}
	return nil
}

func (x *Response) GetError() *ErrorResult {
	if x != nil {
		if x, ok := x.Result.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isResponse_Result interface {
	isResponse_Result()
}

type Response_Success struct {
	Success *SuccessResult `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type Response_Error struct {
	Error *ErrorResult `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*Response_Success) isResponse_Result() {}

func (*Response_Error) isResponse_Result() {}

type ErrorResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Action        ErrorResult_Action     `protobuf:"varint,1,opt,name=action,proto3,enum=mangaplus_api.ErrorResult_Action" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResult) Reset() {
	*x = ErrorResult{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResult) ProtoMessage() {}

func (x *ErrorResult) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResult.ProtoReflect.Descriptor instead.
func (*ErrorResult) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{1}
}

func (x *ErrorResult) GetAction() ErrorResult_Action {
	if x != nil {
		return x.Action
	}
	return ErrorResult_DEFAULT
}

type SuccessResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	RegisterationData *RegistrationData      `protobuf:"bytes,2,opt,name=registerationData,proto3" json:"registerationData,omitempty"`
	TitleDetailView   *TitleDetailView       `protobuf:"bytes,8,opt,name=titleDetailView,proto3" json:"titleDetailView,omitempty"`
	MangaViewer       *MangaViewer           `protobuf:"bytes,10,opt,name=mangaViewer,proto3" json:"mangaViewer,omitempty"`
	SearchView        *SearchView            `protobuf:"bytes,35,opt,name=searchView,proto3" json:"searchView,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SuccessResult) Reset() {
	*x = SuccessResult{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuccessResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResult) ProtoMessage() {}

func (x *SuccessResult) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResult.ProtoReflect.Descriptor instead.
func (*SuccessResult) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{2}
}

func (x *SuccessResult) GetRegisterationData() *RegistrationData {
	if x != nil {
		return x.RegisterationData
	}
	return nil
}

func (x *SuccessResult) GetTitleDetailView() *TitleDetailView {
	if x != nil {
		return x.TitleDetailView
	}
	return nil
}

func (x *SuccessResult) GetMangaViewer() *MangaViewer {
	if x != nil {
		return x.MangaViewer
	}
	return nil
}

func (x *SuccessResult) GetSearchView() *SearchView {
	if x != nil {
		return x.SearchView
	}
	return nil
}

type MangaViewer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pages         []*Page                `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MangaViewer) Reset() {
	*x = MangaViewer{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MangaViewer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MangaViewer) ProtoMessage() {}

func (x *MangaViewer) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MangaViewer.ProtoReflect.Descriptor instead.
func (*MangaViewer) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{3}
}

func (x *MangaViewer) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

type RegistrationData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceSecret  string                 `protobuf:"bytes,1,opt,name=deviceSecret,proto3" json:"deviceSecret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationData) Reset() {
	*x = RegistrationData{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationData) ProtoMessage() {}

func (x *RegistrationData) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationData.ProtoReflect.Descriptor instead.
func (*RegistrationData) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{4}
}

func (x *RegistrationData) GetDeviceSecret() string {
	if x != nil {
		return x.DeviceSecret
	}
	return ""
}

type SearchView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TopSearchBanners []*Banner              `protobuf:"bytes,1,rep,name=topSearchBanners,proto3" json:"topSearchBanners,omitempty"`
	AllTags          []*Tag                 `protobuf:"bytes,2,rep,name=allTags,proto3" json:"allTags,omitempty"`
	AllTitlesGroup   []*AllTitlesGroup      `protobuf:"bytes,3,rep,name=allTitlesGroup,proto3" json:"allTitlesGroup,omitempty"`
	Contents         []*Contents            `protobuf:"bytes,5,rep,name=contents,proto3" json:"contents,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SearchView) Reset() {
	*x = SearchView{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchView) ProtoMessage() {}

func (x *SearchView) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchView.ProtoReflect.Descriptor instead.
func (*SearchView) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{5}
}

func (x *SearchView) GetTopSearchBanners() []*Banner {
	if x != nil {
		return x.TopSearchBanners
	}
	return nil
}

func (x *SearchView) GetAllTags() []*Tag {
	if x != nil {
		return x.AllTags
	}
	return nil
}

func (x *SearchView) GetAllTitlesGroup() []*AllTitlesGroup {
	if x != nil {
		return x.AllTitlesGroup
	}
	return nil
}

func (x *SearchView) GetContents() []*Contents {
	if x != nil {
		return x.Contents
	}
	return nil
}

type Contents struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Banner           *Banner                `protobuf:"bytes,1,opt,name=banner,proto3" json:"banner,omitempty"`
	TitleList        *TitleList             `protobuf:"bytes,2,opt,name=titleList,proto3" json:"titleList,omitempty"`
	RankedTitles     []*TitleRankingGroup   `protobuf:"bytes,3,rep,name=rankedTitles,proto3" json:"rankedTitles,omitempty"`
	AllLabels        []*Label               `protobuf:"bytes,4,rep,name=allLabels,proto3" json:"allLabels,omitempty"`
	ChapterPagesList *ChapterPageList       `protobuf:"bytes,5,opt,name=chapterPagesList,proto3" json:"chapterPagesList,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Contents) Reset() {
	*x = Contents{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Contents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Contents) ProtoMessage() {}

func (x *Contents) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Contents.ProtoReflect.Descriptor instead.
func (*Contents) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{6}
}

func (x *Contents) GetBanner() *Banner {
	if x != nil {
		return x.Banner
	}
	return nil
}

func (x *Contents) GetTitleList() *TitleList {
	if x != nil {
		return x.TitleList
	}
	return nil
}

func (x *Contents) GetRankedTitles() []*TitleRankingGroup {
	if x != nil {
		return x.RankedTitles
	}
	return nil
}

func (x *Contents) GetAllLabels() []*Label {
	if x != nil {
		return x.AllLabels
	}
	return nil
}

func (x *Contents) GetChapterPagesList() *ChapterPageList {
	if x != nil {
		return x.ChapterPagesList
	}
	return nil
}

type TitleRankingGroup struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	OriginalTitleId int32                  `protobuf:"varint,1,opt,name=originalTitleId,proto3" json:"originalTitleId,omitempty"`
	Titles          []*Title               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	Score           int32                  `protobuf:"varint,3,opt,name=score,proto3" json:"score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TitleRankingGroup) Reset() {
	*x = TitleRankingGroup{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleRankingGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleRankingGroup) ProtoMessage() {}

func (x *TitleRankingGroup) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleRankingGroup.ProtoReflect.Descriptor instead.
func (*TitleRankingGroup) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{7}
}

func (x *TitleRankingGroup) GetOriginalTitleId() int32 {
	if x != nil {
		return x.OriginalTitleId
	}
	return 0
}

func (x *TitleRankingGroup) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *TitleRankingGroup) GetScore() int32 {
	if x != nil {
		return x.Score
	}
	return 0
}

type TitleList struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ListName       string                 `protobuf:"bytes,1,opt,name=listName,proto3" json:"listName,omitempty"`
	FeaturedTitles []*Title               `protobuf:"bytes,2,rep,name=featuredTitles,proto3" json:"featuredTitles,omitempty"`
	ContainerId    int32                  `protobuf:"varint,3,opt,name=containerId,proto3" json:"containerId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TitleList) Reset() {
	*x = TitleList{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleList) ProtoMessage() {}

func (x *TitleList) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleList.ProtoReflect.Descriptor instead.
func (*TitleList) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{8}
}

func (x *TitleList) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *TitleList) GetFeaturedTitles() []*Title {
	if x != nil {
		return x.FeaturedTitles
	}
	return nil
}

func (x *TitleList) GetContainerId() int32 {
	if x != nil {
		return x.ContainerId
	}
	return 0
}

type ChapterPageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListName      string                 `protobuf:"bytes,1,opt,name=listName,proto3" json:"listName,omitempty"`
	ChapterPages  []*ChapterPages        `protobuf:"bytes,2,rep,name=chapterPages,proto3" json:"chapterPages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChapterPageList) Reset() {
	*x = ChapterPageList{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterPageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterPageList) ProtoMessage() {}

func (x *ChapterPageList) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterPageList.ProtoReflect.Descriptor instead.
func (*ChapterPageList) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{9}
}

func (x *ChapterPageList) GetListName() string {
	if x != nil {
		return x.ListName
	}
	return ""
}

func (x *ChapterPageList) GetChapterPages() []*ChapterPages {
	if x != nil {
		return x.ChapterPages
	}
	return nil
}

type ChapterPages struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ContainerId      int32                  `protobuf:"varint,1,opt,name=containerId,proto3" json:"containerId,omitempty"`
	ChapterId        int32                  `protobuf:"varint,2,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	TitleId          int32                  `protobuf:"varint,3,opt,name=titleId,proto3" json:"titleId,omitempty"`
	Name             string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Author           string                 `protobuf:"bytes,5,opt,name=author,proto3" json:"author,omitempty"`
	FavoriteImageUrl string                 `protobuf:"bytes,6,opt,name=favoriteImageUrl,proto3" json:"favoriteImageUrl,omitempty"`
	Pages            []*Page                `protobuf:"bytes,7,rep,name=pages,proto3" json:"pages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChapterPages) Reset() {
	*x = ChapterPages{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChapterPages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChapterPages) ProtoMessage() {}

func (x *ChapterPages) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChapterPages.ProtoReflect.Descriptor instead.
func (*ChapterPages) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{10}
}

func (x *ChapterPages) GetContainerId() int32 {
	if x != nil {
		return x.ContainerId
	}
	return 0
}

func (x *ChapterPages) GetChapterId() int32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *ChapterPages) GetTitleId() int32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *ChapterPages) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChapterPages) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *ChapterPages) GetFavoriteImageUrl() string {
	if x != nil {
		return x.FavoriteImageUrl
	}
	return ""
}

func (x *ChapterPages) GetPages() []*Page {
	if x != nil {
		return x.Pages
	}
	return nil
}

type Tag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Slug          string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{11}
}

func (x *Tag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *Tag) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type Banner struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Id            int32                  `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Banner) Reset() {
	*x = Banner{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Banner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Banner) ProtoMessage() {}

func (x *Banner) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Banner.ProtoReflect.Descriptor instead.
func (*Banner) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{12}
}

func (x *Banner) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Banner) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Banner) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Banner) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type AllTitlesGroup struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	TheTitle                  string                 `protobuf:"bytes,1,opt,name=theTitle,proto3" json:"theTitle,omitempty"`
	Titles                    []*Title               `protobuf:"bytes,2,rep,name=titles,proto3" json:"titles,omitempty"`
	Tags                      []*Tag                 `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	Label                     *Label                 `protobuf:"bytes,4,opt,name=label,proto3" json:"label,omitempty"`
	NextChapterStartTimestamp int64                  `protobuf:"varint,5,opt,name=nextChapterStartTimestamp,proto3" json:"nextChapterStartTimestamp,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AllTitlesGroup) Reset() {
	*x = AllTitlesGroup{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllTitlesGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllTitlesGroup) ProtoMessage() {}

func (x *AllTitlesGroup) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllTitlesGroup.ProtoReflect.Descriptor instead.
func (*AllTitlesGroup) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{13}
}

func (x *AllTitlesGroup) GetTheTitle() string {
	if x != nil {
		return x.TheTitle
	}
	return ""
}

func (x *AllTitlesGroup) GetTitles() []*Title {
	if x != nil {
		return x.Titles
	}
	return nil
}

func (x *AllTitlesGroup) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *AllTitlesGroup) GetLabel() *Label {
	if x != nil {
		return x.Label
	}
	return nil
}

func (x *AllTitlesGroup) GetNextChapterStartTimestamp() int64 {
	if x != nil {
		return x.NextChapterStartTimestamp
	}
	return 0
}

type Title struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TitleId           int32                  `protobuf:"varint,1,opt,name=titleId,proto3" json:"titleId,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Author            string                 `protobuf:"bytes,3,opt,name=author,proto3" json:"author,omitempty"`
	PortraitImageUrl  string                 `protobuf:"bytes,4,opt,name=portraitImageUrl,proto3" json:"portraitImageUrl,omitempty"`
	LandscapeImageUrl string                 `protobuf:"bytes,5,opt,name=landscapeImageUrl,proto3" json:"landscapeImageUrl,omitempty"`
	ViewCount         int32                  `protobuf:"varint,6,opt,name=viewCount,proto3" json:"viewCount,omitempty"`
	Language          Language               `protobuf:"varint,7,opt,name=language,proto3,enum=mangaplus_api.Language" json:"language,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Title) Reset() {
	*x = Title{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Title) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Title) ProtoMessage() {}

func (x *Title) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Title.ProtoReflect.Descriptor instead.
func (*Title) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{14}
}

func (x *Title) GetTitleId() int32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *Title) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Title) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Title) GetPortraitImageUrl() string {
	if x != nil {
		return x.PortraitImageUrl
	}
	return ""
}

func (x *Title) GetLandscapeImageUrl() string {
	if x != nil {
		return x.LandscapeImageUrl
	}
	return ""
}

func (x *Title) GetViewCount() int32 {
	if x != nil {
		return x.ViewCount
	}
	return 0
}

func (x *Title) GetLanguage() Language {
	if x != nil {
		return x.Language
	}
	return Language_ENGLISH
}

type Label struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Label) Reset() {
	*x = Label{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Label) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Label) ProtoMessage() {}

func (x *Label) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Label.ProtoReflect.Descriptor instead.
func (*Label) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{15}
}

func (x *Label) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Label) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type TitleDetailView struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Title            *Title                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	TitleImageUrl    string                 `protobuf:"bytes,2,opt,name=titleImageUrl,proto3" json:"titleImageUrl,omitempty"`
	Overview         string                 `protobuf:"bytes,3,opt,name=overview,proto3" json:"overview,omitempty"`
	FirstChapterList []*Chapter             `protobuf:"bytes,9,rep,name=firstChapterList,proto3" json:"firstChapterList,omitempty"`
	LastChapterList  []*Chapter             `protobuf:"bytes,10,rep,name=lastChapterList,proto3" json:"lastChapterList,omitempty"`
	ChapterListV2    []*Chapter             `protobuf:"bytes,38,rep,name=chapterListV2,proto3" json:"chapterListV2,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TitleDetailView) Reset() {
	*x = TitleDetailView{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TitleDetailView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TitleDetailView) ProtoMessage() {}

func (x *TitleDetailView) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TitleDetailView.ProtoReflect.Descriptor instead.
func (*TitleDetailView) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{16}
}

func (x *TitleDetailView) GetTitle() *Title {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *TitleDetailView) GetTitleImageUrl() string {
	if x != nil {
		return x.TitleImageUrl
	}
	return ""
}

func (x *TitleDetailView) GetOverview() string {
	if x != nil {
		return x.Overview
	}
	return ""
}

func (x *TitleDetailView) GetFirstChapterList() []*Chapter {
	if x != nil {
		return x.FirstChapterList
	}
	return nil
}

func (x *TitleDetailView) GetLastChapterList() []*Chapter {
	if x != nil {
		return x.LastChapterList
	}
	return nil
}

func (x *TitleDetailView) GetChapterListV2() []*Chapter {
	if x != nil {
		return x.ChapterListV2
	}
	return nil
}

type Chapter struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TitleId          int32                  `protobuf:"varint,1,opt,name=titleId,proto3" json:"titleId,omitempty"`
	ChapterId        int32                  `protobuf:"varint,2,opt,name=chapterId,proto3" json:"chapterId,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	SubTitle         string                 `protobuf:"bytes,4,opt,name=subTitle,proto3" json:"subTitle,omitempty"`
	ThumbnailUrl     string                 `protobuf:"bytes,5,opt,name=thumbnailUrl,proto3" json:"thumbnailUrl,omitempty"`
	StartTimeStamp   int64                  `protobuf:"varint,6,opt,name=startTimeStamp,proto3" json:"startTimeStamp,omitempty"`
	EndTimeStamp     int64                  `protobuf:"varint,7,opt,name=endTimeStamp,proto3" json:"endTimeStamp,omitempty"`
	AlreadyViewed    bool                   `protobuf:"varint,8,opt,name=alreadyViewed,proto3" json:"alreadyViewed,omitempty"`
	IsVerticalOnly   bool                   `protobuf:"varint,9,opt,name=isVerticalOnly,proto3" json:"isVerticalOnly,omitempty"`
	IsHorizontalOnly bool                   `protobuf:"varint,12,opt,name=isHorizontalOnly,proto3" json:"isHorizontalOnly,omitempty"`
	IsUpdated        bool                   `protobuf:"varint,15,opt,name=isUpdated,proto3" json:"isUpdated,omitempty"`
	ChapterType      int32                  `protobuf:"varint,16,opt,name=chapterType,proto3" json:"chapterType,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Chapter) Reset() {
	*x = Chapter{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chapter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chapter) ProtoMessage() {}

func (x *Chapter) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chapter.ProtoReflect.Descriptor instead.
func (*Chapter) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{17}
}

func (x *Chapter) GetTitleId() int32 {
	if x != nil {
		return x.TitleId
	}
	return 0
}

func (x *Chapter) GetChapterId() int32 {
	if x != nil {
		return x.ChapterId
	}
	return 0
}

func (x *Chapter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Chapter) GetSubTitle() string {
	if x != nil {
		return x.SubTitle
	}
	return ""
}

func (x *Chapter) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *Chapter) GetStartTimeStamp() int64 {
	if x != nil {
		return x.StartTimeStamp
	}
	return 0
}

func (x *Chapter) GetEndTimeStamp() int64 {
	if x != nil {
		return x.EndTimeStamp
	}
	return 0
}

func (x *Chapter) GetAlreadyViewed() bool {
	if x != nil {
		return x.AlreadyViewed
	}
	return false
}

func (x *Chapter) GetIsVerticalOnly() bool {
	if x != nil {
		return x.IsVerticalOnly
	}
	return false
}

func (x *Chapter) GetIsHorizontalOnly() bool {
	if x != nil {
		return x.IsHorizontalOnly
	}
	return false
}

func (x *Chapter) GetIsUpdated() bool {
	if x != nil {
		return x.IsUpdated
	}
	return false
}

func (x *Chapter) GetChapterType() int32 {
	if x != nil {
		return x.ChapterType
	}
	return 0
}

type Page struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MangaPage     *Page_MangaPage        `protobuf:"bytes,1,opt,name=mangaPage,proto3" json:"mangaPage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page) Reset() {
	*x = Page{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page) ProtoMessage() {}

func (x *Page) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page.ProtoReflect.Descriptor instead.
func (*Page) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{18}
}

func (x *Page) GetMangaPage() *Page_MangaPage {
	if x != nil {
		return x.MangaPage
	}
	return nil
}

type Page_MangaPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	Width         int32                  `protobuf:"varint,2,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Page_MangaPage) Reset() {
	*x = Page_MangaPage{}
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Page_MangaPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Page_MangaPage) ProtoMessage() {}

func (x *Page_MangaPage) ProtoReflect() protoreflect.Message {
	mi := &file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Page_MangaPage.ProtoReflect.Descriptor instead.
func (*Page_MangaPage) Descriptor() ([]byte, []int) {
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP(), []int{18, 0}
}

func (x *Page_MangaPage) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *Page_MangaPage) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Page_MangaPage) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_scraper_internal_adapter_mangapluspb_mangaplus_api_proto protoreflect.FileDescriptor

const file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDesc = "" +
	"\n" +
	"8scraper/internal/adapter/mangapluspb/mangaplus_api.proto\x12\rmangaplus_api\"\x82\x01\n" +
	"\bResponse\x128\n" +
	"\asuccess\x18\x01 \x01(\v2\x1c.mangaplus_api.SuccessResultH\x00R\asuccess\x122\n" +
	"\x05error\x18\x02 \x01(\v2\x1a.mangaplus_api.ErrorResultH\x00R\x05errorB\b\n" +
	"\x06result\"\x96\x01\n" +
	"\vErrorResult\x129\n" +
	"\x06action\x18\x01 \x01(\x0e2!.mangaplus_api.ErrorResult.ActionR\x06action\"L\n" +
	"\x06Action\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\x10\n" +
	"\fUNAUTHORIZED\x10\x01\x12\x0f\n" +
	"\vMAINTENANCE\x10\x02\x12\x12\n" +
	"\x0eGEOIP_BLOCKING\x10\x03\"\xa1\x02\n" +
	"\rSuccessResult\x12M\n" +
	"\x11registerationData\x18\x02 \x01(\v2\x1f.mangaplus_api.RegistrationDataR\x11registerationData\x12H\n" +
	"\x0ftitleDetailView\x18\b \x01(\v2\x1e.mangaplus_api.TitleDetailViewR\x0ftitleDetailView\x12<\n" +
	"\vmangaViewer\x18\n" +
	" \x01(\v2\x1a.mangaplus_api.MangaViewerR\vmangaViewer\x129\n" +
	"\n" +
	"searchView\x18# \x01(\v2\x19.mangaplus_api.SearchViewR\n" +
	"searchView\"8\n" +
	"\vMangaViewer\x12)\n" +
	"\x05pages\x18\x01 \x03(\v2\x13.mangaplus_api.PageR\x05pages\"6\n" +
	"\x10RegistrationData\x12\"\n" +
	"\fdeviceSecret\x18\x01 \x01(\tR\fdeviceSecret\"\xf9\x01\n" +
	"\n" +
	"SearchView\x12A\n" +
	"\x10topSearchBanners\x18\x01 \x03(\v2\x15.mangaplus_api.BannerR\x10topSearchBanners\x12,\n" +
	"\aallTags\x18\x02 \x03(\v2\x12.mangaplus_api.TagR\aallTags\x12E\n" +
	"\x0eallTitlesGroup\x18\x03 \x03(\v2\x1d.mangaplus_api.AllTitlesGroupR\x0eallTitlesGroup\x123\n" +
	"\bcontents\x18\x05 \x03(\v2\x17.mangaplus_api.ContentsR\bcontents\"\xb7\x02\n" +
	"\bContents\x12-\n" +
	"\x06banner\x18\x01 \x01(\v2\x15.mangaplus_api.BannerR\x06banner\x126\n" +
	"\ttitleList\x18\x02 \x01(\v2\x18.mangaplus_api.TitleListR\ttitleList\x12D\n" +
	"\frankedTitles\x18\x03 \x03(\v2 .mangaplus_api.TitleRankingGroupR\frankedTitles\x122\n" +
	"\tallLabels\x18\x04 \x03(\v2\x14.mangaplus_api.LabelR\tallLabels\x12J\n" +
	"\x10chapterPagesList\x18\x05 \x01(\v2\x1e.mangaplus_api.ChapterPageListR\x10chapterPagesList\"\x81\x01\n" +
	"\x11TitleRankingGroup\x12(\n" +
	"\x0foriginalTitleId\x18\x01 \x01(\x05R\x0foriginalTitleId\x12,\n" +
	"\x06titles\x18\x02 \x03(\v2\x14.mangaplus_api.TitleR\x06titles\x12\x14\n" +
	"\x05score\x18\x03 \x01(\x05R\x05score\"\x87\x01\n" +
	"\tTitleList\x12\x1a\n" +
	"\blistName\x18\x01 \x01(\tR\blistName\x12<\n" +
	"\x0efeaturedTitles\x18\x02 \x03(\v2\x14.mangaplus_api.TitleR\x0efeaturedTitles\x12 \n" +
	"\vcontainerId\x18\x03 \x01(\x05R\vcontainerId\"n\n" +
	"\x0fChapterPageList\x12\x1a\n" +
	"\blistName\x18\x01 \x01(\tR\blistName\x12?\n" +
	"\fchapterPages\x18\x02 \x03(\v2\x1b.mangaplus_api.ChapterPagesR\fchapterPages\"\xeb\x01\n" +
	"\fChapterPages\x12 \n" +
	"\vcontainerId\x18\x01 \x01(\x05R\vcontainerId\x12\x1c\n" +
	"\tchapterId\x18\x02 \x01(\x05R\tchapterId\x12\x18\n" +
	"\atitleId\x18\x03 \x01(\x05R\atitleId\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\x12*\n" +
	"\x10favoriteImageUrl\x18\x06 \x01(\tR\x10favoriteImageUrl\x12)\n" +
	"\x05pages\x18\a \x03(\v2\x13.mangaplus_api.PageR\x05pages\"+\n" +
	"\x03Tag\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\"b\n" +
	"\x06Banner\x12\x1a\n" +
	"\bimageUrl\x18\x01 \x01(\tR\bimageUrl\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\x05R\x02id\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height\"\xec\x01\n" +
	"\x0eAllTitlesGroup\x12\x1a\n" +
	"\btheTitle\x18\x01 \x01(\tR\btheTitle\x12,\n" +
	"\x06titles\x18\x02 \x03(\v2\x14.mangaplus_api.TitleR\x06titles\x12&\n" +
	"\x04tags\x18\x03 \x03(\v2\x12.mangaplus_api.TagR\x04tags\x12*\n" +
	"\x05label\x18\x04 \x01(\v2\x14.mangaplus_api.LabelR\x05label\x12<\n" +
	"\x19nextChapterStartTimestamp\x18\x05 \x01(\x03R\x19nextChapterStartTimestamp\"\xfa\x01\n" +
	"\x05Title\x12\x18\n" +
	"\atitleId\x18\x01 \x01(\x05R\atitleId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06author\x18\x03 \x01(\tR\x06author\x12*\n" +
	"\x10portraitImageUrl\x18\x04 \x01(\tR\x10portraitImageUrl\x12,\n" +
	"\x11landscapeImageUrl\x18\x05 \x01(\tR\x11landscapeImageUrl\x12\x1c\n" +
	"\tviewCount\x18\x06 \x01(\x05R\tviewCount\x123\n" +
	"\blanguage\x18\a \x01(\x0e2\x17.mangaplus_api.LanguageR\blanguage\"?\n" +
	"\x05Label\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"\xc3\x02\n" +
	"\x0fTitleDetailView\x12*\n" +
	"\x05title\x18\x01 \x01(\v2\x14.mangaplus_api.TitleR\x05title\x12$\n" +
	"\rtitleImageUrl\x18\x02 \x01(\tR\rtitleImageUrl\x12\x1a\n" +
	"\boverview\x18\x03 \x01(\tR\boverview\x12B\n" +
	"\x10firstChapterList\x18\t \x03(\v2\x16.mangaplus_api.ChapterR\x10firstChapterList\x12@\n" +
	"\x0flastChapterList\x18\n" +
	" \x03(\v2\x16.mangaplus_api.ChapterR\x0flastChapterList\x12<\n" +
	"\rchapterListV2\x18& \x03(\v2\x16.mangaplus_api.ChapterR\rchapterListV2\"\x9b\x03\n" +
	"\aChapter\x12\x18\n" +
	"\atitleId\x18\x01 \x01(\x05R\atitleId\x12\x1c\n" +
	"\tchapterId\x18\x02 \x01(\x05R\tchapterId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1a\n" +
	"\bsubTitle\x18\x04 \x01(\tR\bsubTitle\x12\"\n" +
	"\fthumbnailUrl\x18\x05 \x01(\tR\fthumbnailUrl\x12&\n" +
	"\x0estartTimeStamp\x18\x06 \x01(\x03R\x0estartTimeStamp\x12\"\n" +
	"\fendTimeStamp\x18\a \x01(\x03R\fendTimeStamp\x12$\n" +
	"\ralreadyViewed\x18\b \x01(\bR\ralreadyViewed\x12&\n" +
	"\x0eisVerticalOnly\x18\t \x01(\bR\x0eisVerticalOnly\x12*\n" +
	"\x10isHorizontalOnly\x18\f \x01(\bR\x10isHorizontalOnly\x12\x1c\n" +
	"\tisUpdated\x18\x0f \x01(\bR\tisUpdated\x12 \n" +
	"\vchapterType\x18\x10 \x01(\x05R\vchapterType\"\x9a\x01\n" +
	"\x04Page\x12;\n" +
	"\tmangaPage\x18\x01 \x01(\v2\x1d.mangaplus_api.Page.MangaPageR\tmangaPage\x1aU\n" +
	"\tMangaPage\x12\x1a\n" +
	"\bimageUrl\x18\x01 \x01(\tR\bimageUrl\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x03 \x01(\x05R\x06height*\x93\x01\n" +
	"\bLanguage\x12\v\n" +
	"\aENGLISH\x10\x00\x12\v\n" +
	"\aSPANISH\x10\x01\x12\n" +
	"\n" +
	"\x06FRENCH\x10\x02\x12\x0e\n" +
	"\n" +
	"INDONESIAN\x10\x03\x12\x11\n" +
	"\rPORTUGUESE_BR\x10\x04\x12\v\n" +
	"\aRUSSIAN\x10\x05\x12\b\n" +
	"\x04THAI\x10\x06\x12\n" +
	"\n" +
	"\x06GERMAN\x10\a\x12\v\n" +
	"\aITALIAN\x10\b\x12\x0e\n" +
	"\n" +
	"VIETNAMESE\x10\tBDZBgithub.com/aeswibon/manga-cdc/scraper/internal/adapter/mangapluspbb\x06proto3"

var (
	file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescOnce sync.Once
	file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescData []byte
)

func file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescGZIP() []byte {
	file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescOnce.Do(func() {
		file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDesc), len(file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDesc)))
	})
	return file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDescData
}

var file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_goTypes = []any{
	(Language)(0),             // 0: mangaplus_api.Language
	(ErrorResult_Action)(0),   // 1: mangaplus_api.ErrorResult.Action
	(*Response)(nil),          // 2: mangaplus_api.Response
	(*ErrorResult)(nil),       // 3: mangaplus_api.ErrorResult
	(*SuccessResult)(nil),     // 4: mangaplus_api.SuccessResult
	(*MangaViewer)(nil),       // 5: mangaplus_api.MangaViewer
	(*RegistrationData)(nil),  // 6: mangaplus_api.RegistrationData
	(*SearchView)(nil),        // 7: mangaplus_api.SearchView
	(*Contents)(nil),          // 8: mangaplus_api.Contents
	(*TitleRankingGroup)(nil), // 9: mangaplus_api.TitleRankingGroup
	(*TitleList)(nil),         // 10: mangaplus_api.TitleList
	(*ChapterPageList)(nil),   // 11: mangaplus_api.ChapterPageList
	(*ChapterPages)(nil),      // 12: mangaplus_api.ChapterPages
	(*Tag)(nil),               // 13: mangaplus_api.Tag
	(*Banner)(nil),            // 14: mangaplus_api.Banner
	(*AllTitlesGroup)(nil),    // 15: mangaplus_api.AllTitlesGroup
	(*Title)(nil),             // 16: mangaplus_api.Title
	(*Label)(nil),             // 17: mangaplus_api.Label
	(*TitleDetailView)(nil),   // 18: mangaplus_api.TitleDetailView
	(*Chapter)(nil),           // 19: mangaplus_api.Chapter
	(*Page)(nil),              // 20: mangaplus_api.Page
	(*Page_MangaPage)(nil),    // 21: mangaplus_api.Page.MangaPage
}
var file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_depIdxs = []int32{
	4,  // 0: mangaplus_api.Response.success:type_name -> mangaplus_api.SuccessResult
	3,  // 1: mangaplus_api.Response.error:type_name -> mangaplus_api.ErrorResult
	1,  // 2: mangaplus_api.ErrorResult.action:type_name -> mangaplus_api.ErrorResult.Action
	6,  // 3: mangaplus_api.SuccessResult.registerationData:type_name -> mangaplus_api.RegistrationData
	18, // 4: mangaplus_api.SuccessResult.titleDetailView:type_name -> mangaplus_api.TitleDetailView
	5,  // 5: mangaplus_api.SuccessResult.mangaViewer:type_name -> mangaplus_api.MangaViewer
	7,  // 6: mangaplus_api.SuccessResult.searchView:type_name -> mangaplus_api.SearchView
	20, // 7: mangaplus_api.MangaViewer.pages:type_name -> mangaplus_api.Page
	14, // 8: mangaplus_api.SearchView.topSearchBanners:type_name -> mangaplus_api.Banner
	13, // 9: mangaplus_api.SearchView.allTags:type_name -> mangaplus_api.Tag
	15, // 10: mangaplus_api.SearchView.allTitlesGroup:type_name -> mangaplus_api.AllTitlesGroup
	8,  // 11: mangaplus_api.SearchView.contents:type_name -> mangaplus_api.Contents
	14, // 12: mangaplus_api.Contents.banner:type_name -> mangaplus_api.Banner
	10, // 13: mangaplus_api.Contents.titleList:type_name -> mangaplus_api.TitleList
	9,  // 14: mangaplus_api.Contents.rankedTitles:type_name -> mangaplus_api.TitleRankingGroup
	17, // 15: mangaplus_api.Contents.allLabels:type_name -> mangaplus_api.Label
	11, // 16: mangaplus_api.Contents.chapterPagesList:type_name -> mangaplus_api.ChapterPageList
	16, // 17: mangaplus_api.TitleRankingGroup.titles:type_name -> mangaplus_api.Title
	16, // 18: mangaplus_api.TitleList.featuredTitles:type_name -> mangaplus_api.Title
	12, // 19: mangaplus_api.ChapterPageList.chapterPages:type_name -> mangaplus_api.ChapterPages
	20, // 20: mangaplus_api.ChapterPages.pages:type_name -> mangaplus_api.Page
	16, // 21: mangaplus_api.AllTitlesGroup.titles:type_name -> mangaplus_api.Title
	13, // 22: mangaplus_api.AllTitlesGroup.tags:type_name -> mangaplus_api.Tag
	17, // 23: mangaplus_api.AllTitlesGroup.label:type_name -> mangaplus_api.Label
	0,  // 24: mangaplus_api.Title.language:type_name -> mangaplus_api.Language
	16, // 25: mangaplus_api.TitleDetailView.title:type_name -> mangaplus_api.Title
	19, // 26: mangaplus_api.TitleDetailView.firstChapterList:type_name -> mangaplus_api.Chapter
	19, // 27: mangaplus_api.TitleDetailView.lastChapterList:type_name -> mangaplus_api.Chapter
	19, // 28: mangaplus_api.TitleDetailView.chapterListV2:type_name -> mangaplus_api.Chapter
	21, // 29: mangaplus_api.Page.mangaPage:type_name -> mangaplus_api.Page.MangaPage
	30, // [30:30] is the sub-list for method output_type
	30, // [30:30] is the sub-list for method input_type
	30, // [30:30] is the sub-list for extension type_name
	30, // [30:30] is the sub-list for extension extendee
	0,  // [0:30] is the sub-list for field type_name
}

func init() { file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_init() }
func file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_init() {
	if File_scraper_internal_adapter_mangapluspb_mangaplus_api_proto != nil {
		return
	}
	file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes[0].OneofWrappers = []any{
		(*Response_Success)(nil),
		(*Response_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDesc), len(file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_goTypes,
		DependencyIndexes: file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_depIdxs,
		EnumInfos:         file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_enumTypes,
		MessageInfos:      file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_msgTypes,
	}.Build()
	File_scraper_internal_adapter_mangapluspb_mangaplus_api_proto = out.File
	file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_goTypes = nil
	file_scraper_internal_adapter_mangapluspb_mangaplus_api_proto_depIdxs = nil
}
