name: deploy-manual-gcp
version: 1
stages:
  - id: deploy-gcp
    workflow: .github/workflows/stage-deploy-gcp.yml
    inputs:
      image_tag: ${IMAGE_TAG}
      deployment_target: ${DEPLOYMENT_TARGET}
      deploy_method: ${DEPLOY_METHOD}

  - id: deploy-vercel
    workflow: .github/workflows/stage-deploy-vercel.yml
    needs:
      - deploy-gcp
