apiVersion: apps/v1
kind: Deployment
metadata:
  name: connect
  namespace: manga-cdc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: connect
  template:
    metadata:
      labels:
        app: connect
    spec:
      containers:
        - name: connect
          image: debezium/connect:2.7.3.Final
          ports:
            - containerPort: 8083
          envFrom:
            - configMapRef:
                name: manga-cdc-config
          livenessProbe:
            httpGet:
              path: /
              port: 8083
            initialDelaySeconds: 60
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /connectors
              port: 8083
            initialDelaySeconds: 30
            periodSeconds: 10
