apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manga-cdc
  namespace: manga-cdc
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - manga-cdc.example.com
      secretName: manga-cdc-tls
  rules:
    - host: manga-cdc.example.com
      http:
        paths:
          - path: /api/notifications
            pathType: Prefix
            backend:
              service:
                name: notification-service
                port:
                  number: 8080
          - path: /kafka
            pathType: Prefix
            backend:
              service:
                name: kafkaui
                port:
                  number: 8085
          - path: /grafana
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
