apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redpanda
  namespace: manga-cdc
spec:
  serviceName: redpanda
  replicas: 1
  selector:
    matchLabels:
      app: redpanda
  template:
    metadata:
      labels:
        app: redpanda
    spec:
      containers:
        - name: redpanda
          image: docker.redpanda.com/redpandadata/redpanda:v24.2.7
          ports:
            - containerPort: 9092
            - containerPort: 9644
          command:
            - redpanda
            - start
            - --kafka-addr internal://0.0.0.0:9092
            - --advertise-kafka-addr internal://redpanda:9092
            - --pandaproxy-addr internal://0.0.0.0:8082
            - --advertise-pandaproxy-addr internal://redpanda:8082
            - --schema-registry-addr internal://0.0.0.0:8081
            - --rpc-addr redpanda:33145
            - --advertise-rpc-addr redpanda:33145
            - --mode dev-container
            - --smp 1
            - --memory 512M
          livenessProbe:
            exec:
              command: ["rpk", "cluster", "info"]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["rpk", "cluster", "info"]
            initialDelaySeconds: 10
            periodSeconds: 5
