apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: manga-cdc-secrets
  namespace: manga-cdc
spec:
  encryptedData:
    discord-webhook-url: ""
  template:
    metadata:
      name: manga-cdc-secrets
    type: Opaque
